# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: dfkossi/fizzbuzz
  tag: 0.1.2
  pullPolicy: IfNotPresent

service:
  name: fizzbuzz
  type: NodePort
  externalPort: 3000
  internalPort: 3000

resources: {}


